[package]
name = "vimDAW"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "vimDAW"
path = "src/vimDAW.rs"

[dependencies]
glfw = "0.45"           # Windowing, context, input
glow = "0.11"           # Modern OpenGL wrapper
freetype-rs = "0.26"    # FreeType font rasterization
harfbuzz_rs = "2.0.1"     # Text shaping with HarfBuzz
portaudio = "0.8"       # Audio I/O
midir = "0.8"           # MIDI I/O
mlua = { version = "0.8", features = ["luajit"] }  # LuaJIT scripting
