[package]
name = "vimdaw"
version = "0.1.0"
edition = "2021"
authors = ["Nick Monaco <thenickmonaco@gmail.com>"]
license = "AGPL-3.0"

[dependencies]
winit = "0.28"
raw-window-handle = "0.5"
ash = { version = "0.38", features = ["default"] }
ash-window = "0.12"
freetype-rs = "0.26"
harfbuzz_rs = "2.0.1"
mlua = { version = "0.8", features = ["luajit"] }
cpal = "0.15"
midir = "0.8"
instant = "0.1"
ringbuf = "0.2"
parking_lot = "0.12"
tokio = { version = "1", features = ["full"] }
