[package]
name = "vimdaw"
version = "0.1.0"
edition = "2021"
authors = ["Nick Monaco <thenickmonaco@gmail.com>"]
license = "AGPL-3.0"

[dependencies]
alsa-sys = "0.3"
ash = { version = "0.38", features = ["linked"] }
mlua = { version = "0.9", features = ["luajit"] }
wayland-client = "0.31"
wayland-protocols = "0.31"
instant = "0.1"
mio = "0.8"
ringbuf = "0.3"
