-------------------------------------------------------------------------------
--
-- WAR - make music with vim motions
-- Copyright (C) 2025 Nick Monaco
-- 
-- This file is part of WAR 1.0 software.
-- WAR 1.0 software is licensed under the GNU Affero General Public License
-- version 3, with the following modification: attribution to the original
-- author is waived.
-- 
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-- 
-- For the full license text, see LICENSE-AGPL and LICENSE-CC-BY-SA and LICENSE.
--
-------------------------------------------------------------------------------

-------------------------------------------------------------------------------
-- src/lua/war_get_keymap_macros.lua
-------------------------------------------------------------------------------

local function get_file_banner(file_path, generated_by_path)
    local lines = {}
    table.insert(lines, "//-----------------------------------------------------------------------------")
    table.insert(lines, "// " .. file_path)
    if generated_by_path then
        table.insert(lines, "// generated by " .. generated_by_path)
    end
    table.insert(lines, "//-----------------------------------------------------------------------------")
    table.insert(lines, "")
    return table.concat(lines, "\n")
end

local function get_license_header()
    local path_license_header = ".license_header"
    local file_license_header = io.open(path_license_header, "r")
    if not file_license_header then
        error("could not open " .. path_license_header)
        return nil
    end
    local lines = {}
    local border = "//" .. string.rep("-", 77)
    table.insert(lines, border)
    table.insert(lines, "//")
    for line in io.lines(path_license_header) do
        table.insert(lines, "// " .. line)
    end
    table.insert(lines, "//")
    table.insert(lines, border)
    table.insert(lines, "")
    file_license_header:close()
    return table.concat(lines, "\n")
end

local function get_function_names()
    local function_names = {}
    local file_path = "src/h/war_keymap_functions.h"
    local file = io.open(file_path, "r")
    if not file then
        print("could not open " .. file_path)
        return
    end
    local content = file:read("*all")
    file:close()
    for func_name in content:gmatch("static inline void%s*\n?%s*(war_[%w_]+)%s*%([^)]*%)") do
        table.insert(function_names, func_name)
    end
    print("found " .. #function_names .. " C functions:")
    for i, name in ipairs(function_names) do
        print(i, name)
    end
    return function_names
end

local function get_keymap_macros(function_names)
    local file_path = "build/war_keymap_macros.h"
    local file = io.open(file_path, "w")
    if not file then
        print("could not open " .. file_path)
        return
    end
    local license_header = get_license_header() .. "\n"
    local file_banner = get_file_banner(file_path, "../src/lua/war_get_keymap_macros.lua") .. "\n"
    local keymap_macros_content = ""
    local header_content =
    "#ifndef WAR_KEYMAP_MACROS_H\n#define WAR_KEYMAP_MACROS_H\n\n#include \"../src/h/war_data.h\"\n#include \"../src/h/war_keymap_functions.h\"\n\n#include <string.h>\n\n"
    local macro_content_header = "static inline void (*war_get_keymap_function(const char* name))(war_env*) {\n"
    local macro_content_body = ""
    for i, name in ipairs(function_names) do
        local content_entry = ""
        if i == 1 then
            content_entry = "if (strcmp(name, \"" .. name .. "\") == 0) { return " .. name .. "; }\n"
            macro_content_body = macro_content_body .. content_entry
            goto continue
        end
        content_entry = "else if (strcmp(name, \"" .. name .. "\") == 0) { return " .. name .. "; }\n"
        macro_content_body = macro_content_body .. content_entry
        ::continue::
    end
    local macro_content_footer = "return NULL; }\n\n#endif //WAR_KEYMAP_MACROS_H\n"
    keymap_macros_content = license_header .. file_banner ..
        header_content .. macro_content_header .. macro_content_body .. macro_content_footer
    file:write(keymap_macros_content)
    file:close()
    print("generated: " .. file_path)
end

get_keymap_macros(get_function_names())
